---
- name: Instalar .NET Core 8 y configurar la aplicación de cell shop
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Actualizar el sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalando las dependencias
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Descargar el paquete de repositorio de Microsoft para Ubuntu 22.04 LTS
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb

    - name: Instalar el paquete de repositorio de Microsoft
      dpkg:
        name: /tmp/packages-microsoft-prod.deb
        state: present

    - name: Actualizar el caché de apt después de agregar el repositorio
      apt:
        update_cache: yes

    - name: Instalar .NET SDK
      apt:
        name: dotnet-sdk-8.0
        state: present

    - name: Crear directorio para la aplicación del cell
      file:
        path: /home/ubuntu/cell
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Crear archivo del proyecto
      copy:
        dest: /home/ubuntu/cell/cell.csproj
        content: |
          <Project Sdk="Microsoft.NET.Sdk.Web">
            <PropertyGroup>
              <TargetFramework>net8.0</TargetFramework>
            </PropertyGroup>
          </Project>
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Crear archivo de código fuente Program.cs
      copy:
        dest: /home/ubuntu/cell/Program.cs
        content: |
          // (Tu código C# aquí)
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Construir la aplicación de cell
      command: dotnet build
      args:
        chdir: /home/ubuntu/cell
      become_user: ubuntu

    - name: Crear archivo de servicio systemd para la aplicación
      copy:
        dest: /etc/systemd/system/cell.service
        content: |
          [Unit]
          Description=Cell Shop Application
          After=network.target

          [Service]
          WorkingDirectory=/home/ubuntu/cell
          ExecStart=/usr/bin/dotnet /home/ubuntu/cell/bin/Debug/net8.0/cell.dll --urls "http://0.0.0.0:5000"
          Restart=always
          RestartSec=10
          SyslogIdentifier=cell-app
          User=ubuntu
          Environment=ASPNETCORE_ENVIRONMENT=Production

          [Install]
          WantedBy=multi-user.target
      mode: '0644'

    - name: Recargar systemd
      command: systemctl daemon-reload

    - name: Iniciar y habilitar la aplicación cell shop
      systemd:
        name: cell.service
        state: started
        enabled: yes
